HTTP5204_PassionProject_N01437602/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HTTP5204_PassionProject_N01437602.Models
{
    public class User
    {
        [Key]
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserName { get; set; }
        public string UserLocation { get; set; }
        public string UserBio { get; set; }
        public bool UserHasPic { get; set; }


        //Gets extension of image if user has one
        public string UserPicExtension { get; set; }

        //A User can own many products
        public ICollection<Product> Product { get; set; }

    }


        public class UserDto
        {
            public int UserID { get; set; }
            
            [DisplayName("First Name")]
            public string UserFirstName { get; set; }
            [DisplayName("Last Name")]
            public string UserLastName { get; set; }
            [DisplayName("Username")]
            public string UserName { get; set; }
            [DisplayName("Location")]
            public string UserLocation { get; set; }
            [DisplayName("Bio")]
            public string UserBio { get; set; }

            public bool UserHasPic { get; set; }
            public string UserPicExtension { get; set; }

        }
}

HTTP5204_PassionProject_N01437602/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HTTP5204_PassionProject_N01437602.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;

namespace HTTP5204_PassionProject_N01437602.Controllers
{
    public class ProductController : Controller
    {

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;

        static ProductController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);

            client.BaseAddress = new Uri("https://localhost:44302/api/");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        }

        // GET: Product/List
        public ActionResult List(string search)
        {
            string url = "productdata/getproducts";
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                IEnumerable<ProductDto> SelectedProduct = response.Content.ReadAsAsync<IEnumerable<ProductDto>>().Result;
                return View(search == null ? SelectedProduct :
                    SelectedProduct.Where(x => x.ProductName.IndexOf(search, StringComparison.OrdinalIgnoreCase) >= 0).ToList());
            }
            else
            {
                return RedirectToAction("Error");
            }
        }


        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            ShowProduct ViewModel = new ShowProduct();
            string url = "productdata/findproduct/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                //Puts data into product DTO
                ProductDto SelectedProduct = response.Content.ReadAsAsync<ProductDto>().Result;
                ViewModel.product = SelectedProduct;

                //Finds user that owns product, buts data into user DTO
                url = "productdata/finduserforproduct/" + id;
                response = client.GetAsync(url).Result;
                UserDto SelectedUser = response.Content.ReadAsAsync<UserDto>().Result;
                ViewModel.user = SelectedUser;

                return View(ViewModel);

            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            UpdateProduct ViewModel = new UpdateProduct();

            return View(ViewModel);
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product ProductInfo)
        {
            Debug.WriteLine(ProductInfo.ProductName);
            string url = "productdata/addproduct";
            Debug.WriteLine(jss.Serialize(ProductInfo));
            HttpContent content = new StringContent(jss.Serialize(ProductInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                int productid = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", new { id = productid });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            UpdateProduct ViewModel = new UpdateProduct();

            string url = "productdata/findproduct/" + id;

            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                ProductDto SelectedProduct = response.Content.ReadAsAsync<ProductDto>().Result;
                ViewModel.product = SelectedProduct;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, Product ProductInfo, HttpPostedFileBase ProductPic)
        {
            Debug.WriteLine(ProductInfo.ProductName);
            string url = "productdata/updateproduct/" + id;
            Debug.WriteLine(jss.Serialize(ProductInfo));
            HttpContent content = new StringContent(jss.Serialize(ProductInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response.StatusCode);

            if (response.IsSuccessStatusCode)
            {

                url = "productdata/updateproductpic/" + id;

                if (ProductPic == null)
                {
                    return RedirectToAction("Details", new { id = id });
                }
                Debug.WriteLine("Received product picture " + ProductPic.FileName);
                //Error when NULL

                MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                HttpContent imagecontent = new StreamContent(ProductPic.InputStream);
                requestcontent.Add(imagecontent, "ProductPic", ProductPic.FileName);
                response = client.PostAsync(url, requestcontent).Result;


                return RedirectToAction("Details", new { id = id });

            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Product/Delete/5
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "productdata/findproduct/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                ProductDto SelectedProduct = response.Content.ReadAsAsync<ProductDto>().Result;
                return View(SelectedProduct);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Product/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string url = "productdata/deleteproduct/" + id;

            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

HTTP5204_PassionProject_N01437602/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HTTP5204_PassionProject_N01437602.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;

namespace HTTP5204_PassionProject_N01437602.Controllers
{
    public class UserController : Controller
    {

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;
        private StoreDbContext db = new StoreDbContext();

        static UserController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);

            client.BaseAddress = new Uri("https://localhost:44302/api/");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        }


        // GET: User/List
        public ActionResult List(string search)
        {
            string url = "userdata/getusers";
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                IEnumerable<UserDto> SelectedUser = response.Content.ReadAsAsync<IEnumerable<UserDto>>().Result;
                return View(search == null ? SelectedUser :
                    SelectedUser.Where(x => x.UserFirstName.IndexOf(search, StringComparison.OrdinalIgnoreCase) >=0 
                    || x.UserLastName.IndexOf(search, StringComparison.OrdinalIgnoreCase) >= 0 
                    || x.UserName.IndexOf(search, StringComparison.OrdinalIgnoreCase) >= 0).ToList());
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {

            ShowUser ViewModel = new ShowUser();
            string url = "userdata/finduser/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            
            if (response.IsSuccessStatusCode)
            {
                //Puts data into user DTO
                UserDto SelectedUser = response.Content.ReadAsAsync<UserDto>().Result;
                ViewModel.user = SelectedUser;

                url = "userdata/getproductsforuser/" + id;
                response = client.GetAsync(url).Result;
                Debug.WriteLine(response.StatusCode);
                IEnumerable<ProductDto> SelectedProduct = response.Content.ReadAsAsync<IEnumerable<ProductDto>>().Result;
                ViewModel.userproducts = SelectedProduct;

                return View(ViewModel);

            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: User/Create
        public ActionResult Create()
        {
            UpdateUser ViewModel = new UpdateUser();

            return View(ViewModel);
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User UserInfo)
        {
            Debug.WriteLine(UserInfo.UserFirstName);
            string url = "userdata/adduser";
            Debug.WriteLine(jss.Serialize(UserInfo));
            HttpContent content = new StringContent(jss.Serialize(UserInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            
            if (response.IsSuccessStatusCode)
            {
                int userid = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", new { id = userid });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            UpdateUser ViewModel = new UpdateUser();

            string url = "userdata/finduser/" + id;

            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                UserDto SelectedUser = response.Content.ReadAsAsync<UserDto>().Result;
                ViewModel.user = SelectedUser;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }       


        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, User UserInfo, HttpPostedFileBase UserPic)
        {
            Debug.WriteLine(UserInfo.UserFirstName);
            string url = "userdata/updateuser/" + id;
            Debug.WriteLine(jss.Serialize(UserInfo));
            HttpContent content = new StringContent(jss.Serialize(UserInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response.StatusCode);

            if (response.IsSuccessStatusCode)
            {

                url = "userdata/updateuserpic/" + id;
                
                if (UserPic == null)
                {
                    return RedirectToAction("Details", new { id = id });
                }
                Debug.WriteLine("Received user picture " + UserPic.FileName);
                //Error when NULL

                MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                HttpContent imagecontent = new StreamContent(UserPic.InputStream);
                requestcontent.Add(imagecontent, "UserPic", UserPic.FileName);
                response = client.PostAsync(url, requestcontent).Result;
                

                return RedirectToAction("Details", new { id = id });
                
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        
        // GET: User/Delete/5
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "userdata/finduser/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                UserDto SelectedUser = response.Content.ReadAsAsync<UserDto>().Result;
                return View(SelectedUser);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: User/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string url = "userdata/deleteuser/" + id;

            
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if(response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }



        public ActionResult Error()
        {
            return View();
        }
    }
}

HTTP5204_PassionProject_N01437602/Views/User/Create.cshtml
@model HTTP5204_PassionProject_N01437602.Models.UpdateUser

@{
    ViewBag.Title = "Create";
}

<h2>New User</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Fill in the information below to create a new user.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.user.UserFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user.UserFirstName, new { htmlAttributes = new { @class = "form-control", Name = "UserFirstName" } })
                @Html.ValidationMessageFor(model => model.user.UserFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user.UserLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user.UserLastName, new { htmlAttributes = new { @class = "form-control", Name = "UserLastName" } })
                @Html.ValidationMessageFor(model => model.user.UserLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user.UserName, new { htmlAttributes = new { @class = "form-control", Name = "UserName" } })
                @Html.ValidationMessageFor(model => model.user.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user.UserLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user.UserLocation, new { htmlAttributes = new { @class = "form-control", Name = "UserLocation" } })
                @Html.ValidationMessageFor(model => model.user.UserLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user.UserBio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user.UserBio, new { htmlAttributes = new { @class = "form-control", Name = "UserBio" } })
                @Html.ValidationMessageFor(model => model.user.UserBio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

HTTP5204_PassionProject_N01437602/Views/User/DeleteConfirm.cshtml
@model HTTP5204_PassionProject_N01437602.Models.UserDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>Are you sure you want to delete @Model.UserFirstName @Model.UserLastName?</h2>

<h3 class="warning">Warning: This action cannot be reversed.</h3>

@Html.ActionLink("Cancel", "List")
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserBio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserBio)
        </dd>
    </dl>

    @using (Html.BeginForm("Delete", "User", new { id = Model.UserID }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

HTTP5204_PassionProject_N01437602/Views/User/Details.cshtml
@model HTTP5204_PassionProject_N01437602.Models.ShowUser

@{
    ViewBag.Title = "Details";
}

<h2>Full Name: @Model.user.UserFirstName @Model.user.UserLastName</h2>
<h3>Username: @Model.user.UserName</h3>
<hr />

<div class="viewContainer">
    @{
        string pic = "/Content/Users/default-user-icon.jpg";
        string alt = "No Profile Picture Provided";
        if (Model.user.UserHasPic)
        {
            pic = "/Content/Users/" + Model.user.UserID + "." + Model.user.UserPicExtension;
            alt = "User image of " + Model.user.UserName;
        }
    }

    <div class="imgContainer">
        <img src="@pic" alt="@alt" />
    </div>

    <div class="detailContainer">
        <h4>User Information</h4>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.user.UserFirstName):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.user.UserFirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.user.UserLastName):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.user.UserLastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.user.UserName):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.user.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.user.UserLocation):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.user.UserLocation)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.user.UserBio):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.user.UserBio)
            </dd>
        </dl>
    </div>

    <div class="detailContainer">
        <h4>Products Owned</h4>
        <div class="dl-horizontal">
            @foreach (var product in Model.userproducts)
            {
                <div>
                    @Html.ActionLink(product.ProductName, "Details", "Product", new { id = product.ProductID }, new { })
                </div>
            }
        </div>
    </div>
</div>

    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.user.UserID }) |
        @Html.ActionLink("Back to User List", "List")
    </p>

HTTP5204_PassionProject_N01437602/Views/User/Edit.cshtml
@model HTTP5204_PassionProject_N01437602.Models.UpdateUser

@{
    ViewBag.Title = "View";
}

<h2>Update</h2>

<div class="editContainer">
    @using (Html.BeginForm("Edit", "User", new { id = Model.user.UserID }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Please update your information here.</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.user.UserID, new { Name = "UserID" })

            <div class="form-group">
                @Html.LabelFor(model => model.user.UserFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.user.UserFirstName, new { htmlAttributes = new { @class = "form-control", Name = "UserFirstName" } })
                    @Html.ValidationMessageFor(model => model.user.UserFirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.user.UserLastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.user.UserLastName, new { htmlAttributes = new { @class = "form-control", Name = "UserLastName" } })
                    @Html.ValidationMessageFor(model => model.user.UserLastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.user.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.user.UserName, new { htmlAttributes = new { @class = "form-control", Name = "UserName" } })
                    @Html.ValidationMessageFor(model => model.user.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.user.UserLocation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.user.UserLocation, new { htmlAttributes = new { @class = "form-control", Name = "UserLocation" } })
                    @Html.ValidationMessageFor(model => model.user.UserLocation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.user.UserBio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.user.UserBio, new { htmlAttributes = new { @class = "form-control", Name = "UserBio" } })
                    @Html.ValidationMessageFor(model => model.user.UserBio, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10"><input type="file" name="UserPic" class="imgBtn" /></div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div class="viewContainer">
        @{
            string pic = "/Content/Users/default-Product-icon.jpg";
            string alt = "No User Picture Provided";
            if (Model.user.UserHasPic)
            {
                pic = "/Content/Users/" + Model.user.UserID + "." + Model.user.UserPicExtension;
                alt = "Product image of " + Model.user.UserName;
            }
        }

        <div class="imgContainer">
            <h4>Current Image</h4>
            <img src="@pic" alt="@alt" />
        </div>
    </div>
</div>


    <div>
        @Html.ActionLink("Back to List", "List")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

HTTP5204_PassionProject_N01437602/Views/User/List.cshtml
@model IEnumerable<HTTP5204_PassionProject_N01437602.Models.UserDto>

@{
    ViewBag.Title = "List";
}

<h2>User Database</h2>

<p>
    @Html.ActionLink("Add User", "Create")
</p>

<p>
    @using (Html.BeginForm("List", "User", FormMethod.Get))
    {
    @Html.TextBox("search") <input type="submit" value="search" />
    }
</p>

<p>@Html.ActionLink("View Full User List", "List")</p>

<table class="table">

    @if (Model.Count() == 0)
    {
        <p>There are no results for that search.</p>
    }
    else
    {

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th></th>
        </tr>

        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserFirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserLastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.UserID }) |
                    @Html.ActionLink("View Details", "Details", new { id = item.UserID }) |
                    @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.UserID })
                </td>
            </tr>
        }
    }

</table>